### ISSUE TITLE
Use ApplyOutOfSyncOnly for all addons

### ISSUE THREAD

**Issue by csantanapr** [gitops-bridge-dev/gitops-bridge-argocd-control-plane-template#10]
Some charts have too many resources and is better to do selective sync

```yaml
spec:
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
```
