### ISSUE TITLE
make addon argocd application names lower case

### ISSUE THREAD

**Issue by csantanapr** [gitops-bridge-dev/gitops-bridge-argocd-control-plane-template#47]
In all addons argocd app follow the pattern to specify the name using cluster name, but the cluster name can have upper case letters like using EKS cluster name "Carlos Cluster" we need to lower case and replace space with underscore

For example in https://github.com/gitops-bridge-dev/gitops-bridge-argocd-control-plane-template/blob/main/bootstrap/control-plane/addons/aws/addons-aws-load-balancer-controller-appset.yaml#L41
```yaml
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}
```

We need to convert appset to goTemplate issue #46 
Then use sprig function lower for example
```yaml
  template:
    metadata:
      name: addon-{{.name | lower}}-{{.values.addonChart}}
```
